name: Github Action
on: [push]
jobs:
  Explore:
    runs-on: ubuntu-latest
    steps:
      - name: add zsh
        run: |
          sudo apt update
          sudo apt install -y zsh

      - name: hello
        shell: zsh
        run: echo hello world $0
